Repository Kurbamit/PSP2, pull requests merged in 2024-12, with the labels that each got.

#15 Employee FE
  ReactApp1/ReactApp1.Server/Controllers/Domain/EmployeeController.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/EmployeeRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/IEmployeeRepository.cs
  ReactApp1/ReactApp1.Server/Models/Models/Domain/EmployeeModel.cs
  ReactApp1/ReactApp1.Server/Services/EmployeeService.cs
  ReactApp1/ReactApp1.Server/Services/IEmployeeService.cs
  ReactApp1/reactapp1.client/src/App.tsx
  ReactApp1/reactapp1.client/src/assets/resources/strings.ts
  ReactApp1/reactapp1.client/src/components/Domain/Employee/EmployeeDetail.tsx
  ReactApp1/reactapp1.client/src/components/Domain/Employee/Employees.tsx
Labels: FE

#20 Create order endpoints (Part 1)
  ReactApp1/ReactApp1.Server/Controllers/Domain/OrderController.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/FullOrderRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/IFullOrderRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/IItemRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/IOrderRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/ItemRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/OrderRepository.cs
  ReactApp1/ReactApp1.Server/Models/Models/Domain/FullOrderModel.cs
  ReactApp1/ReactApp1.Server/Models/Models/Domain/OrderModel.cs
  ReactApp1/ReactApp1.Server/Models/Models/Domain/StorageModel.cs
  ReactApp1/ReactApp1.Server/Program.cs
  ReactApp1/ReactApp1.Server/Services/IOrderService.cs
  ReactApp1/ReactApp1.Server/Services/OrderService.cs
Labels: BE

#21 Search template
  ReactApp1/ReactApp1.Server/Controllers/Base/LoginController.cs
  ReactApp1/ReactApp1.Server/Controllers/Domain/SharedSearchesController.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/ISharedSearchesRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/SharedSearchesRepository.cs
  ReactApp1/ReactApp1.Server/Extensions/QueryableExtensions.cs
  ReactApp1/ReactApp1.Server/Models/Models/Base/SharedItem.cs
  ReactApp1/ReactApp1.Server/Program.cs
  ReactApp1/ReactApp1.Server/Services/ISharedSearchesService.cs
  ReactApp1/ReactApp1.Server/Services/SharedSearchesService.cs
  ReactApp1/reactapp1.client/package-lock.json
  ReactApp1/reactapp1.client/package.json
  ReactApp1/reactapp1.client/src/App.tsx
  ReactApp1/reactapp1.client/src/components/Base/SelectDropdown.tsx
  ReactApp1/reactapp1.client/src/components/Domain/Item/ItemDetail.tsx
Labels: FE, BE

#24 Create order endpoints (Part 2)
  ReactApp1/ReactApp1.Server/Controllers/Domain/OrderController.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/FullOrderRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/IFullOrderRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/IOrderRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/OrderRepository.cs
  ReactApp1/ReactApp1.Server/Models/Models/Domain/OrderModel.cs
  ReactApp1/ReactApp1.Server/Services/IOrderService.cs
  ReactApp1/ReactApp1.Server/Services/OrderService.cs
Labels: BE

#26 Add global exception handling middleware
  ReactApp1/ReactApp1.Server/Exceptions/BaseException.cs
  ReactApp1/ReactApp1.Server/Exceptions/ItemNotFoundException.cs
  ReactApp1/ReactApp1.Server/Middlewares/ErrorHandlerMiddleware.cs
  ReactApp1/ReactApp1.Server/Program.cs
Labels: BE

#27 Added item count in order
  README.md
  ReactApp1/reactapp1.client/package-lock.json
  ReactApp1/reactapp1.client/package.json
  ReactApp1/reactapp1.client/src/assets/resources/strings.ts
  ReactApp1/reactapp1.client/src/components/Domain/Employee/Employees.tsx
  ReactApp1/reactapp1.client/src/components/Domain/Item/Items.tsx
  ReactApp1/reactapp1.client/src/components/Domain/Order/OrderDetail.tsx
  ReactApp1/reactapp1.client/src/components/Domain/Order/Orders.tsx
Labels: FE

#17 Establishment CRUD
  CHANGELOG.md
  ReactApp1/ReactApp1.Server/Controllers/Base/EstablishmentController.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/EstablishmentRepository.cs
  ReactApp1/ReactApp1.Server/Data/Repositories/IEstablishmentRepository.cs
  ReactApp1/ReactApp1.Server/Models/Models/Domain/EstablishmentModel.cs
  ReactApp1/ReactApp1.Server/Program.cs
  ReactApp1/ReactApp1.Server/Services/EstablishmentService.cs
  ReactApp1/ReactApp1.Server/Services/IEstablishmentService.cs
Labels: BE

#31 Alerts
  ReactApp1/ReactApp1.Server/Controllers/Domain/SharedSearchesController.cs
  ReactApp1/ReactApp1.Server/Services/ISharedSearchesService.cs
  ReactApp1/ReactApp1.Server/Services/SharedSearchesService.cs
  ReactApp1/reactapp1.client/index.html
  ReactApp1/reactapp1.client/src/App.css
  ReactApp1/reactapp1.client/src/App.tsx
  ReactApp1/reactapp1.client/src/assets/Utils/axiosInterceptor.ts
  ReactApp1/reactapp1.client/src/components/Base/ErrorContext.tsx
  ReactApp1/reactapp1.client/src/components/Base/GlobalAlert.tsx
  ReactApp1/reactapp1.client/src/components/Domain/Order/Orders.tsx
Labels: FE

#42 Create unit tests project
  ReactApp1/ReactApp1.Server.UnitTest/ReactApp1.Server.UnitTest.csproj
  ReactApp1/ReactApp1.Server.UnitTest/TestOrderService.cs
  ReactApp1/ReactApp1.Server/Models/Models/Domain/StorageModel.cs
  ReactApp1/ReactApp1.Server/Services/OrderService.cs
  ReactApp1/ReactApp1.sln
Labels: BE

#48 Task/reservation sms
  CHANGELOG.md
  ReactApp1/ReactApp1.Server/Program.cs
  ReactApp1/ReactApp1.Server/ReactApp1.Server.csproj
  ReactApp1/ReactApp1.Server/Services/ReservationService.cs
  ReactApp1/ReactApp1.Server/appsettings.json
Labels: enhancement, BE
